plain_entities_general = {
    '': ' ',
    'copy': '\u00a9',
    'times': '\u00d7',
    'divide': '\u00f7',
    'minus': '\u2212',
    'pm': '\u00b1',
    'plusmn': '\u00b1',
    'radic': '\u221a',
    'cent': '\u00a2',
    'pound': '\u00a3',
    'euro': '\u20ac',
    'reg': '\u00ae',
    'laquo': '\u00ab',
    'raquo': '\u00bb',
    'sup2': '\u00b2;',
    'sup3': '\u00b3',
    'grave': '\u0060',
    'acute': '\u00b4',
    'lsquo': '\u2018',
    'rsquo': '\u2019',
    'ldquo': '\u201c',
    'rdquo': '\u201d',
}

html_entities_general = {
    '': '&nbsp;',
    'copy': '&copy;',
    'times': '&times;',
    'divide': '&divide;',
    'minus': '&minus;',
    'pm': '&plusmn;',
    'radic': '&radic;',
    'cent': '&cent;',
    'pound': '&pound;',
    'euro': '&euro;',
    'reg': '&reg;',
    'laquo': '&laquo',
    'raquo': '&raquo',
    'sup2': '&sup2;',
    'sup3': '&sup3;',
    'grave': '&grave;',
    'acute': '&acute;',
    'lsquo': '&lsquo;',
    'rsquo': '&rsquo;',
    'ldquo': '&ldquo;',
    'rdquo': '&rdquo;',
}

plain_entities_greek = {
    'Alpha': '\u0391',
    'Beta': '\u0392',
    'Chi': '\u03a7',
    'Delta': '\u0394',
    'Epsilon': '\u0395',
    'Eta': '\u0397',
    'Gamma': '\u0393',
    'Iota': '\u0399',
    'Kappa': '\u039a',
    'Lambda': '\u039b',
    'Mu': '\u039c',
    'Nu': '\u039d',
    'Omega': '\u03a9',
    'Omicron': '\u039f',
    'Phi': '\u03a6',
    'Pi': '\u03a0',
    'Psi': '\u03a8',
    'Rho': '\u03a1',
    'Sigma': '\u03a3',
    'Tau': '\u03a4',
    'Theta': '\u0398',
    'Upsilon': '\u03a5',
    'Xi': '\u039e',
    'Zeta': '\u0396',
    'alpha': '\u03b1',
    'beta': '\u03b2',
    'chi': '\u03c7',
    'delta': '\u03b4',
    'epsilon': '\u03b5',
    'eta': '\u03b7',
    'gamma': '\u03b3',
    'iota': '\u03b9',
    'kappa': '\u03ba',
    'lambda': '\u03bb',
    'mu': '\u03bc',
    'nu': '\u03bd',
    'omega': '\u03c9',
    'omicron': '\u03bf',
    'phi': '\u03c6',
    'pi': '\u03c0',
    'piv': '\u03d6',
    'psi': '\u03c8',
    'rho': '\u03c1',
    'sigma': '\u03c3',
    'sigmaf': '\u03c2',
    'tau': '\u03c4',
    'theta': '\u03b8',
    'thetasym': '\u03d1',
    'upsih': '\u03d2',
    'upsilon': '\u03c5',
    'xi': '\u03be',
    'zeta': '\u03b6',
}

html_entities_greek = {
    'Alpha': '&Alpha;',
    'Beta': '&Beta;',
    'Chi': '&Chi;',
    'Delta': '&Delta;',
    'Epsilon': '&Epsilon;',
    'Eta': '&Eta;',
    'Gamma': '&Gamma;',
    'Iota': '&Iota;',
    'Kappa': '&Kappa;',
    'Lambda': '&Lambda;',
    'Mu': '&Mu;',
    'Nu': '&Nu;',
    'Omega': '&Omega;',
    'Omicron': '&Omicron;',
    'Phi': '&Phi;',
    'Pi': '&Pi;',
    'Psi': '&Psi;',
    'Rho': '&Rho;',
    'Sigma': '&Sigma;',
    'Tau': '&Tau;',
    'Theta': '&Theta;',
    'Upsilon': '&Upsilon;',
    'Xi': '&Xi;',
    'Zeta': '&Zeta;',
    'alpha': '&alpha;',
    'beta': '&beta;',
    'chi': '&chi;',
    'delta': '&delta;',
    'epsilon': '&epsilon;',
    'eta': '&eta;',
    'gamma': '&gamma;',
    'iota': '&iota;',
    'kappa': '&kappa;',
    'lambda': '&lambda;',
    'mu': '&mu;',
    'nu': '&nu;',
    'omega': '&omega;',
    'omicron': '&omicron;',
    'phi': '&phi;',
    'pi': '&pi;',
    'piv': '&piv;',
    'psi': '&psi;',
    'rho': '&rho;',
    'sigma': '&sigma;',
    'sigmaf': '&sigmaf;',
    'tau': '&tau;',
    'theta': '&theta;',
    'thetasym': '&thetasym;',
    'upsih': '&upsih;',
    'upsilon': '&upsilon;',
    'xi': '&xi;',
    'zeta': '&zeta;',
}

plain_entities = plain_entities_general | plain_entities_greek
html_entities = html_entities_general | html_entities_greek

